"""empty message

Revision ID: 32953d1b8596
Revises: a3800f778e1a
Create Date: 2022-12-04 16:26:07.036340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32953d1b8596'
down_revision = 'a3800f778e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favorite_question', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('user_favorite_question', 'question_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_favorite_question', 'question_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('user_favorite_question', 'id')
    # ### end Alembic commands ###
