"""empty message

Revision ID: 6e19aec6e88d
Revises: a404cdd8c85d
Create Date: 2022-11-28 20:22:35.675719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e19aec6e88d'
down_revision = 'a404cdd8c85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('iscollect', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'iscollect')
    # ### end Alembic commands ###
