"""empty message

Revision ID: a404cdd8c85d
Revises: e590356c67ce
Create Date: 2022-11-27 14:51:35.977644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a404cdd8c85d'
down_revision = 'e590356c67ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('num_content', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'num_content')
    # ### end Alembic commands ###
