"""empty message

Revision ID: c4cd8d2a604a
Revises: a016653cffb1
Create Date: 2022-12-04 15:09:48.956963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cd8d2a604a'
down_revision = 'a016653cffb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favorite_question', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_favorite_question', 'id')
    # ### end Alembic commands ###
