"""empty message

Revision ID: e4f350b54a33
Revises: 11c8ba986e68
Create Date: 2022-12-07 10:43:33.883727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f350b54a33'
down_revision = '11c8ba986e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('question', sa.Column('geoloaction', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'geoloaction')
    op.drop_column('question', 'city')
    # ### end Alembic commands ###
